project:
  type: website
  output-dir: docs

website:
  title: "Sean Gardner"
  google-analytics: "G-E5T5MLDTMN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Visualizations.qmd
        text: Visualizations
      - href: Projects.qmd
        text: Projects
      - href: posts.qmd
        text: Blog
    

format:
  html:
    theme:
      - Lux
      - custom.scss
    toc: true
    page-layout: full

editor: visual

