project:
  type: website
  output-dir: docs

website:
  title: "Sean Gardner"
  google-analytics: "G-E5T5MLDTMN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Visualizations.qmd
      - Projects.qmd
      - posts.qmd
    

format:
  html:
    theme:
      - Lux
      - custom.scss
    toc: true
    page-layout: full

editor: visual

